<?php
/**
 * Created by PhpStorm.
 * User: ckhero
 * Date: 2019/2/26
 * Time: 12:21 AM
 */

namespace admin\modules\v1\controllers;


use admin\models\AdminUser;
use common\components\ApiController;
use common\consts\ErrorConst;
use common\exceptions\DefaultException;
use Yii;
use yii\base\Module;

class AdminController extends ApiController
{
    /**
     * @var AdminUser
     */
    public $adminUser;

    public $uri;

    public $whiteList = [
        'v1/user/login',
    ];

    /**
     * @param $action
     * @return bool
     * @throws DefaultException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        $uri = $action->controller->module->id . '/' . $action->controller->id . '/' . $action->id;
        $this->uri = $uri;

//        if (!in_array($this->uri, $this->whiteList)) {
//            $this->adminUser = (new AdminUser())->findByToken(Yii::$app->request->headers->get('x-token'));
//            if (!$this->adminUser) throw new DefaultException(ErrorConst::ERROR_ADMIN_USER_NOT_LOGIN);
//        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}